### ISSUE TITLE
Website offline

### ISSUE THREAD

**Issue by aPollO2k** [AlexAkulov/putty-color-themes#1]
http://putty.org.ru/themes/index.html is down.
Can you please offer a new way to watch the themes?

**Comment by AlexAkulov** [comment]
Hello!
This site is avaliable on [WebArchive](https://web.archive.org/web/20151122030926/http://putty.org.ru:80/themes/index.html) and I have added images in repo, now you can see previews [here](https://github.com/AlexAkulov/putty-color-themes/blob/master/images/readme.md)

**Comment by aPollO2k** [comment]
Thank you very much :)                                                                                                                                                                         Gesendet über BlackBerry Hub für Android                                                                                                                                                                            Von: notifications@github.comGesendet: 6. Juli 2017 20:57An: putty-color-themes@noreply.github.comAntworten: reply@reply.github.comCc: sprungantrieb@gmail.com; author@noreply.github.comBetreff: Re: [AlexAkulov/putty-color-themes] Website offline (#1)  Hello!
This site is avaliable on WebArchive and I have added images in repo, now you can see previews here
